### ISSUE TITLE
compile slideio under arm64 without network connection

### ISSUE THREAD

**Issue by lascqy** [Booritas/slideio#10]
Hi,
    I'm working under a armx64 platform. So, there is not available wheels in the PIPY repo.
    I have to build the wheel from the source codes by myself.
    However, in the source codes, the dependencies are installed by the CONAN. I have no permission to access network on this node. Is there any way I could build the dependencies by myself(offline) and put them under the "testlib" dir, So I could build the wheel for armx64 platform.

many thanks!!!!

**Comment by Booritas** [comment]
Hi,
Thank you for your message. Unfortunately, it is not easy to build the library offline. It consumes a lot of 3rd party components. One of the problem is - conan-center does not provides arm binaries for the most of the components.

It is possible to use the recipes from the conan-center and compile the components on a local computer, but it would require access to the component source code, which is normally located in one of the public git repository and requires online access.
 I started writing an instruction how to pull everything to a local computer and compile the library, but soon realized that it becomes a nightmare. For each component you have to download a conan recipe (all of them are in one git repo), download source code from another git repo, update the recipe to use the downloaded source code instead of online access and compile it. You need to do it for 49 components. I don't think it is manageable. 
I hope, that soon arm binaries become available on the conan server and the build will be easier.
Best regards,
Stanislav

**Comment by lascqy** [comment]
thanks for your answer.
Yes, I also found it is a nightmare after I analysis the dependencies on conan.
Even the source codes of the dependencies on conan are not form the conan website but from many other 3rd websites(official website itself). So I need a full network access not only the conan site in the white list. 
finally,I build a arm wheel with a QEMU virtual machine of arm64 ubuntu locally on my own computer with network access.
And then copy it to the arm cluster.
Also, hopefully, there will be more slideio wheels on the PIPY repo, that's will be much better.

**Comment by Booritas** [comment]
Wow, thanks a lot for the info. I did not think it would work. Would it be possible to share the changes you made to build the software on Arm processor? I can automate the creation of arm wheels on github and make the packages available.
You can use pull request or just send me new/changed files.
Thanks!
