### ISSUE TITLE
Dicom WSI support enhancement

### ISSUE THREAD

**Issue by Assistedevolution** [Booritas/slideio#2]
Hi nice work on the library.
Any thoughts of adding Dicom WSI format and support for jpeg2000 lossless compression

**Comment by Booritas** [comment]
Thanks for your feedback, I'm currently working on the support for DICOM images. I expect it to be ready in approx. 1 month. Jpeg200 so far was not in my list, at least not in the priority list. Since JPEG 2000 is not so widely used for medical purposes. I know that some scanners support export in this format. Maybe it is time to reconsider it.

**Comment by Booritas** [comment]
I just uploaded a new version 2.4.1 that includes support for DICOM WSI files
