### ISSUE TITLE
import slideio

### ISSUE THREAD

**Issue by tramdoan** [Booritas/slideio#30]
Hi, 
I installed slideio using pip in a python virtual environment and it reported successfull installation. However, when I try to import slideio in python to use, I received this error message:

File "/Users/tramdoan/Sydney Uni Dropbox/Tram Doan/scripts/pythonVirtualEnv/lib/python3.12/site-packages/slideio/py_slideio.py", line 8, in <module>
    import slideiopybind as sld
ModuleNotFoundError: No module named 'slideiopybind'

I have checked that /Users/tramdoan/Sydney Uni Dropbox/Tram Doan/scripts/pythonVirtualEnv/lib/python3.12/site-packages is in sys.path. 

I would appreciate your help to troubleshoot this.

Many thanks

**Comment by Booritas** [comment]
Thank you for bringing this to our attention.

I've been able to reproduce the issue, and it appears to affect version 2.6 on certain operating systems. I’m working on a fix and will address it as quickly as possible. 

In the meantime, you can revert to version 2.5 by running the following command:

```
pip install slideio==2.5
```

The main difference between versions 2.5 and 2.6 is the added support for PerkinElmer QPTIFF files.

I’ll notify you as soon as the bug is resolved.
Best regards,
Stanislav

**Comment by Booritas** [comment]
I've just released a new update (v2.6.1) that includes a fix for the bug. You can install it using the pip command. Please note that this update is currently available only for macOS, as the issue did not affect other operating systems.

If you find the library useful, I would greatly appreciate it if you could give the repository a star.

Thank you for your support!

Best regards,
Stanislav

**Comment by Booritas** [comment]
done in version 2.6.1

**Comment by tramdoan** [comment]
Hi Stanislav,
Just wanted to say thank you. I ended up using version 2.5 and it did solved the problem. Thanks again your help and for developing a very useful tool.
