### ISSUE TITLE
RuntimeError when opening VSI file from Olympus VS200

### ISSUE THREAD

**Issue by Yu-AnChen** [Booritas/slideio#34]
Thank you so much for creating and maintaining SlideIO—the prebuilt wheels are a lifesaver! I've been searching for a solution to read Olympus whole-slide VSI files, and SlideIO has been working remarkably well.

However, when trying to open VSI files from the latest slide scanner, the VS200, using the Python API, I'm encountering a `RuntimeError`:

```python
RuntimeError: /Users/runner/work/slideio/slideio/src/slideio/drivers/vsi/etsfile.cpp:93:VSI driver: no volume with size 0x0 found
```

I attempted to identify which ETS file is causing this error. The `scene` ETS file worked fine, but it seems that the “Label” auxiliary file is where SlideIO is encountering issues.

If you and the team are interested in investigating further, you can [download the scan without the `scene` file here (~70MB)](https://www.dropbox.com/scl/fi/bxlpcxq4p75ptqm7e38au/vs200-vsi-share.zip?rlkey=cvroj64jt6mus48r1bwo5kai7&st=2umbkwb0&dl=0). Your help would be much appreciated!

Thanks again for your hard work!

**Comment by Booritas** [comment]
Thank you for using SlideioIO! I confirm that I can reproduce the bug. I'll try to fix it ASAP.

**Comment by Booritas** [comment]
Apologies for the delay. I’ve just uploaded a new version (2.6.3) that includes a fix. The issue lies in the slide's ETS file, specifically "blob_21_f_Frame#0.ets," which is unfortunately corrupted. While recovery from this error wasn’t possible, I’ve enhanced failure tolerance. Now, instead of halting at the first error, the library will continue reading other external files. For this slide, the valid files are auxiliary images labeled "Macro image" and "Overview." Also, note that the num_scenes property for the slide may return 0. You can access the auxiliary images through the get_aux_image_names and get_aux_image methods.
```python
aux_image_names = slide.get_aux_image_names()
aux_scene = slide.get_aux_image(aux_image_names[0])
```

**Comment by Yu-AnChen** [comment]
Awesome, thank you so much for resolving the issue so quickly. Yes I can confirm that v2.6.3 fixed the VSI reading error - can also confirm that the expected auxiliary images can be accessed properly. 

I did remove the ets file of the actual scene in this thread just for trouble shooting. It makes sense to me that the `num_scenes` is 0 in the shared dataset. In the complete dataset the `scene` is present when opened with slideio. 

Thanks again for making and distributing slideio!
