### ISSUE TITLE
Compile from source code，how can I access  slideio conan repository

### ISSUE THREAD

**Issue by yip111** [Booritas/slideio#5]
![image](https://user-images.githubusercontent.com/73650283/176337587-169d3e1a-e73c-42d6-8522-ef618c61ca32.png)
I compile the slideio from source code, but I can't download opencv/4.1.1@slideio/stable from the slideio channel,  it looks like need to login in the private repository,but how can I register this repository?

**Comment by Booritas** [comment]
Thank you for your message. I just enabled anonymous access to my JFrog artifactory. Please try again. Please let me know if you have any problem with the library.
Best regards,
Stanislav

**Comment by yip111** [comment]
Thank you for your reply,but I still can not access the remote repository,it seems to still need to login.can you tell me how to login the slideio conan repository,or tell me  the username and password?
![image](https://user-images.githubusercontent.com/73650283/177077337-781952d1-12fc-4a95-bde6-fbdaa7205c24.png)


Another question,when I follow the README.md and use git clone https://booritas@bitbucket.org/bioslide/slideio.git to get the source code ,it need the  password ,so I use git clone https://github.com/Booritas/slideio.git to get the source code,is that correct?
![image](https://user-images.githubusercontent.com/73650283/177077607-da1f81fb-2e33-4469-bd5c-022ba7801885.png)

**Comment by blitmaps** [comment]
@Booritas , firstly thank you for your work on this library.

The bintray link to your conan repo is dead : https://api.bintray.com/conan/booritas/slideio (returns 410 Gone)

**Comment by Booritas** [comment]
Unfortunately, JFrog closed bintray server. I'm moving the code to their artifactory. I expect it to be ready in 2-3 weeks with the new version of the library. I will renew installation instruction as well. 
Sorry for any inconvenience.
Stanislav

**Comment by blitmaps** [comment]
Thanks Stanislav, that is good to hear.

**Comment by bnapora** [comment]
Thanks for update.  Looking forward to trying the new version

**Comment by oskarthaeter** [comment]
@Booritas Is this fixed? Both `https://bioslide.jfrog.io/artifactory/api/conan/slideio-conan-local` (C++ docs) and `https://bioslide.jfrog.io/artifactory/api/conan/slideio-conan` (Python docs) redirect to a JFrog landing page stating "JFrog's Free-Tier subscription has been deactivated." Any help/guidance to compile the C++ code would be greatly appreciated!

**Comment by Booritas** [comment]
> @Booritas Is this fixed? Both `https://bioslide.jfrog.io/artifactory/api/conan/slideio-conan-local` (C++ docs) and `https://bioslide.jfrog.io/artifactory/api/conan/slideio-conan` (Python docs) redirect to a JFrog landing page stating "JFrog's Free-Tier subscription has been deactivated." Any help/guidance to compile the C++ code would be greatly appreciated!

@oskarthaeter 
Unfortunately, JFrog no longer offers a free server. I was unable to locate an alternative free server. Currently, I am renting a server in the cloud and hosting my own Conan server for this project. I can grant you access to the server; however, please note that I am paying for the service and do not wish to make it publicly available. If you provide me with your email or another private channel where I can send you the Conan-server endpoint, I will gladly do so.

**Comment by oskarthaeter** [comment]
Hi @Booritas
my email is `oskar.thaeter@gmail.com`.
Since this library is much faster than the alternative (Openslide), I'll try to convince my colleagues to try it out. I would also love to contribute (e.g. moving to a newer C++ standard, reducing dependencies, static compilation). Thank you for your invaluable work!

**Comment by Booritas** [comment]
> Hi @Booritas my email is `oskar.thaeter@gmail.com`. Since this library is much faster than the alternative (Openslide), I'll try to convince my colleagues to try it out. I would also love to contribute (e.g. moving to a newer C++ standard, reducing dependencies, static compilation). Thank you for your invaluable work!

I have just forwarded you instructions on how to access the server. I would greatly appreciate any contributions you could make to the project. Please let me know what tasks you are willing to undertake. Presently, I employ static compilation wherever possible. However, there are certain limitations due to the existence of some libraries in multiple versions. For instance, the Hamamatsu NDPI driver utilizes specific TIFF and JPEG libraries that have been modified by the vendor.

Moreover, the adoption of the latest C++ standard is constrained because the library must be compiled across multiple Linux OSs, each equipped with different compilers. Currently, support is provided for most Linux distributions from 2014 onwards. Nevertheless, I am confident that we can enhance everything, including addressing the issues you highlighted.

Thank you for using slideio. Any feedback, including feature requests, are highly appreciated.
